# Generated by Django 5.2.10 on 2026-01-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_appointment_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, verbose_name='Enfermedades crónicas'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='recent_surgeries',
            field=models.TextField(blank=True, verbose_name='Operaciones recientes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='recommended_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Recomendado por'),
        ),
    ]
